name: Register Oracle

on:
  workflow_call:
  workflow_dispatch:

jobs:

  register:
    runs-on: ubuntu-latest

    container:
      image: python:3.11-slim


    env:
      ORACLE_USER: ${{ secrets.ORACLE_USER }}
      ORACLE_PASSWORD: ${{ secrets.ORACLE_PASSWORD }}
      ORACLE_DSN: ${{ secrets.ORACLE_DSN }}
      ORACLE_WALLET_PASSWORD: ${{ secrets.ORACLE_WALLET_PASSWORD }}
      ORACLE_WALLET_BASE64: ${{ secrets.ORACLE_WALLET_BASE64 }}
      ROOT_DIR: ./resource

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: "必要パッケージのインストール" 
        run: | 
          apt-get update && apt-get install -y unzip libaio1 wget
          rm -rf /var/lib/apt/lists/*

      - name: "Oracle Instant Client のダウンロードと展開（任意のバージョンを選んでOK）"
        run: |
          wget https://download.oracle.com/otn_software/linux/instantclient/1918000/instantclient-basic-linux.x64-19.18.0.0.0dbru.zip
          wget https://download.oracle.com/otn_software/linux/instantclient/1918000/instantclient-sdk-linux.x64-19.18.0.0.0dbru.zip
          unzip instantclient-basic-linux.x64-19.18.0.0.0dbru.zip
          unzip instantclient-sdk-linux.x64-19.18.0.0.0dbru.zip
          rm *.zip

      - name: "権限確認"
        run: |  
          ls -l .

      - name: "Pythonライブラリのインストール"
        run: |  
          pip install --no-cache-dir -r ./worker/python/requirements.txt

      - name: "Oracle DB へのデータ挿入"
        run: |
          echo "$ORACLE_WALLET_BASE64" | base64 --decode > wallet.zip
          unzip wallet.zip -d .
          ls -l .
          chown -R $(whoami):$(whoami) ./wallet
          export LD_LIBRARY_PATH=./instantclient_19_18
          python ./worker/python/register.py


